Repository jenkinsci/azure-container-agents-plugin, pull requests merged in 2022-01, with the labels that each got.

#92 Update bom and parent pom
  pom.xml
Labels: chore

#90 Container Instances - Use of Private IPS
  pom.xml
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciAgent.java
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciCleanTask.java
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciContainerTemplate.java
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciPrivateIpAddress.java
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciService.java
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciContainerTemplateBuilder.java
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciContainerTemplateFluent.java
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilder.java
  src/main/java/com/microsoft/jenkins/containeragents/util/InstanceIdentityFacade.java
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciContainerTemplate/config.jelly
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciContainerTemplate/config.properties
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciContainerTemplate/help-privateIpAddress.html
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciPrivateIpAddress/config.jelly
  src/main/resources/com/microsoft/jenkins/containeragents/aci/deployTemplate.json
  src/main/resources/com/microsoft/jenkins/containeragents/aci/networkProfileSnippet.json
  src/test/java/com/microsoft/jenkins/containeragents/JCasCTest.java
  src/test/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilderTest.java
  src/test/resources/com/microsoft/jenkins/containeragents/configuration-as-code.yaml
Labels: enhancement

#95 Use legacy instance id instead of Instance Identity
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilder.java
  src/main/java/com/microsoft/jenkins/containeragents/util/CustomJenkinsFacade.java
  src/main/java/com/microsoft/jenkins/containeragents/util/InstanceIdentityFacade.java
  src/test/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilderTest.java
Labels: skip-changelog

#98 Choose Vnet and subnet from a different resource group
  README.md
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciPrivateIpAddress.java
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilder.java
  src/main/java/com/microsoft/jenkins/containeragents/util/AzureContainerUtils.java
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciContainerTemplate/help-privateIpAddress.html
  src/main/resources/com/microsoft/jenkins/containeragents/aci/AciPrivateIpAddress/config.jelly
  src/test/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilderTest.java
Labels: enhancement

#100 Remove CustomJenkinsFacade
  pom.xml
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilder.java
  src/main/java/com/microsoft/jenkins/containeragents/util/CustomJenkinsFacade.java
  src/test/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilderTest.java
Labels: chore
