Repository jenkinsci/azure-container-agents-plugin, pull requests merged in 2022-03, with the labels that each got.

#107 Enable dependabot on maven dependencies
  .github/dependabot.yml
Labels: chore

#119 If using Private IP Address and resource group of vnet is empty, the resource group is not used from the Azure Container Instance Configuration
  src/main/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilder.java
  src/test/java/com/microsoft/jenkins/containeragents/builders/AciDeploymentTemplateBuilderTest.java
Labels: bug

#117 Update Azure SDK and remove Workaround
  src/main/java/com/microsoft/jenkins/containeragents/aci/AciCloud.java
Labels: enhancement
